TercerPre-EntregaSierra/gym_project/gym_project/urls.py
from django.contrib import admin
from django.urls import path
from gym_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('entrenador_form/', views.entrenador_form, name='entrenador_form'),
    path('registro_form/', views.registro_form, name='registro_form'),
    path('contacto_form/', views.contacto_form, name='contacto_form'),
]

TercerPre-EntregaSierra/gym_project/gym_app/models.py
from django.db import models

class Entrenador(models.Model):
    nombre_completo = models.CharField(max_length=100)
    horario = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre_completo

class Inscripcion(models.Model):
    nombre_completo = models.CharField(max_length=100)
    edad = models.IntegerField()
    MEMBRESIA_CHOICES = [
        ('vip', 'VIP'),
        ('clasico', 'Clásico'),
    ]
    membresia = models.CharField(max_length=10, choices=MEMBRESIA_CHOICES)
    entrenador = models.ForeignKey(Entrenador, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre_completo

class Contacto(models.Model):
    nombre_completo = models.CharField(max_length=100)
    telefono_contacto = models.CharField(max_length=15)
    mail = models.EmailField()
    mensaje = models.TextField()

    def __str__(self):
        return self.nombre_completo

TercerPre-EntregaSierra/gym_project/gym_app/forms.py
from django import forms
from .models import Inscripcion, Entrenador, Contacto

class InscripcionForm(forms.ModelForm):
    class Meta:
        model = Inscripcion
        fields = ['nombre_completo', 'edad', 'membresia', 'entrenador']

class EntrenadorForm(forms.ModelForm):
    HORARIO_CHOICES = [
        ('mañana', 'Mañana'),
        ('tarde', 'Tarde'),
        ('noche', 'Noche'),
    ]
    horario = forms.ChoiceField(choices=HORARIO_CHOICES)

    class Meta:
        model = Entrenador
        fields = ['nombre_completo', 'horario']

class ContactoForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = ['nombre_completo', 'telefono_contacto', 'mail', 'mensaje']

TercerPre-EntregaSierra/gym_project/gym_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import InscripcionForm, EntrenadorForm, ContactoForm
from .models import Inscripcion, Entrenador

def index(request):
    buscarEntrenador = request.GET.get('buscarEntrenador')
    buscarSocio = request.GET.get('buscarSocio')
    entrenadores = []
    socios = []

    if buscarEntrenador:
        entrenadores = Entrenador.objects.filter(nombre_completo__icontains=buscarEntrenador)

    if buscarSocio:
        socios = Inscripcion.objects.filter(nombre_completo__icontains=buscarSocio)

    return render(request, 'index.html', {
        'entrenadores': entrenadores,
        'socios': socios,
    })

def registro_form(request):
    if request.method == 'POST':
        form = InscripcionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = InscripcionForm()

    entrenadores = Entrenador.objects.all()
    return render(request, 'registro_form.html', {'form': form, 'entrenadores': entrenadores})

def entrenador_form(request):
    if request.method == 'POST':
        form = EntrenadorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = EntrenadorForm()
    return render(request, 'entrenador_form.html', {'form': form})

def contacto_form(request):
    if request.method == 'POST':
        form = ContactoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = ContactoForm()
    return render(request, 'contacto_form.html', {'form': form})

TercerPre-EntregaSierra/gym_project/gym_app/templates/contacto_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Contacto</title>
</head>
<body>
    <header class="bg-light w-100">
        <div class="text-center">
            <img src="{% static 'img/banner.png' %}" class="img-fluid mb-4" alt="Banner">
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'index' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'registro_form' %}">Inscripcion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'entrenador_form' %}">Entrenadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contacto_form' %}">Contacto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+hu3a4R7tKRa1A0nwVlEVOxLkXBhp" crossorigin="anonymous"></script>
</body>
</html>

TercerPre-EntregaSierra/gym_project/gym_app/templates/entrenador_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Entrenadores</title>
    <style>
        .form-container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            height: 50vh;
            margin-bottom: 25vh;
        }
    </style>
</head>

<body>
<header class="bg-light w-100">
    <div class="text-center">
        <img src="{% static 'img/banner.png' %}" class="img-fluid mb-4" alt="Banner">
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'registro_form' %}">Inscripción</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contacto_form' %}">Contacto</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<div class="container form-container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" action="{% url 'entrenador_form' %}">
                {% csrf_token %}
                {{ form.as_p }}
                
                <button type="submit" class="btn btn-primary">Registrar</button>
            </form>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+hu3a4R7tKRa1A0nwVlEVOxLkXBhp"
        crossorigin="anonymous"></script>
</body>
</html>

TercerPre-EntregaSierra/gym_project/gym_app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Gimnasio</title>
</head>
<body>
<header class="bg-light w-100">
    <div class="text-center">
        <img src="{% static 'img/banner.png' %}" class="img-fluid mb-4" alt="Banner">
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'registro_form' %}">Inscripcion</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entrenador_form' %}">Entrenadores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contacto_form' %}">Contacto</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <h2>Buscar Entrenador</h2>
            <form method="get" action="{% url 'index' %}">
                <div class="input-group">
                    <input type="text" name="buscarEntrenador" class="form-control" placeholder="Nombre del entrenador">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </div>
            </form>
            {% if entrenadores %}
                <h3 class="mt-5">Lista de Entrenadores</h3>
                <ul class="list-group">
                    {% for entrenador in entrenadores %}
                    <li class="list-group-item">{{ entrenador.nombre_completo }} - {{ entrenador.horario }}</li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="alert alert-warning mt-5">No se encontraron resultados.</div>
            {% endif %}
        </div>
        <div class="col-md-6">
            <h2>Buscar Socio</h2>
            <form method="get" action="{% url 'index' %}">
                <div class="input-group">
                    <input type="text" name="buscarSocio" class="form-control" placeholder="Nombre del socio">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </div>
            </form>
            {% if socios %}
                <h3 class="mt-5">Lista de Socios</h3>
                <ul class="list-group">
                    {% for socio in socios %}
                    <li class="list-group-item">{{ socio.nombre_completo }} - {{ socio.membresia }} - {{ socio.entrenador.nombre_completo }}</li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="alert alert-warning mt-5">No se encontraron resultados.</div>
            {% endif %}
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+hu3a4R7tKRa1A0nwVlEVOxLkXBhp"
        crossorigin="anonymous"></script>
</body>
</html>

TercerPre-EntregaSierra/gym_project/gym_app/templates/registro_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Registro de Socios</title>
    <style>
        .form-container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            height: 50vh;
            margin-bottom: 25vh;
        }
    </style>
</head>
<body>
<header class="bg-light w-100">
    <div class="text-center">
        <img src="{% static 'img/banner.png' %}" class="img-fluid mb-4" alt="Banner">
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entrenador_form' %}">Entrenadores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contacto_form' %}">Contacto</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<div class="container form-container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" action="{% url 'registro_form' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_nombre_completo" class="form-label">Nombre Completo</label>
                    <input type="text" name="nombre_completo" class="form-control" id="id_nombre_completo" required>
                </div>
                <div class="mb-3">
                    <label for="id_edad" class="form-label">Edad</label>
                    <input type="number" name="edad" class="form-control" id="id_edad" required>
                </div>
                <div class="mb-3">
                    <label for="id_membresia" class="form-label">Membresía</label>
                    <select name="membresia" class="form-select" id="id_membresia">
                        <option value="vip">VIP</option>
                        <option value="clasico">Clásico</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label for="id_entrenador" class="form-label">Entrenador</label>
                    <select name="entrenador" class="form-select" id="id_entrenador">
                        {% for entrenador in entrenadores %}
                        <option value="{{ entrenador.id }}">{{ entrenador.nombre_completo }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Registrar</button>
            </form>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+hu3a4R7tKRa1A0nwVlEVOxLkXBhp"
        crossorigin="anonymous"></script>
</body>
</html>